[project]
name = "trellis2-amd"
description = "ComfyUI Wrapper for Microsoft Trellis.2 - Native and Compact Structured Latents for 3D Generation"
version = "1.0.26"
license = {file = "LICENSE"}
classifiers = [
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Environment :: GPU :: AMD ROCm",
]

dependencies = ["meshlib", "requests", "pymeshlab", "opencv-python", "scipy", "open3d", "plotly", "trimesh", "rembg"]

[project.urls]
Repository = "https://github.com/dmonkman/ComfyUI-Trellis2-AMD"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/dmonkman/ComfyUI-Trellis2-AMD#readme"
"Bug Tracker" = "https://github.com/dmonkman/ComfyUI-Trellis2-AMD/issues"
Upstream = "https://github.com/visualbruno/ComfyUI-Trellis2"

[tool.comfy]
PublisherId = "dmonkman"
DisplayName = "ComfyUI-Trellis2-AMD"
Icon = ""
includes = []